version: "3.1"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4583:4583"
    environment:
      - SERVICES=ssm:4583
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - "4583"